export default {
  en: {
    SurahAlKahf: "Surah Al Kahf",
    Pause: "Pause",
    SurahInfo: "Surah Info",
    Reciters: "Reciters",
    Copied: "Copied",
    Settings: "Settings",
    Reading: "Reading",
    Nightmode: "Nightmode",
    Daymode: "Daymode",
    Translations: "Translations",
    Tooltip: "Tooltip",
    FontSize: "Font Size",
    Arabic: "Arabic",
    Translation: "Translation",
    Verses: "Verses",
    Surahs: "Surahs",
    Play: "Play",
    Copy: "Copy",
    NextSurah: "Next Surah",
    PreviousSurah: "Previous Surah",
    BeginningofSurah: "Beginning of Surah",
    Home: "Home",
    Islam: "Islam",
    Help: "Help",
    Feed: "Feedback",
    Contri: "Contribute",
    Mobile: "Mobile",
    Dev: "Developers",
    Langs: "Languages",
    placeholder: "Search Anything...",
    Quick: "Direct link",
    All: "All",
    Makki: "Makki Surahs of Quran",
    Madni: "Madini Surahs of Quran",
    Manzil: "Manzil",
    SurahYasin: "Surah Yasin (Yaseen)",
    SurahArRahman: "Surah Ar-Rahman",
    SurahAlMulk: "Surah Al Mulk",
    AyatulKursi: "Ayatul Kursi",
    Site: "Site",
    Prayer: "Prayer times",
    About: "About Us",
    Contact: "Contact Us",
    Footertext:
      "Al-kitaab.com (also known as the noble quran, al quran, holy quran, koran) is a pro bono project.",
    FootCopy: "2019 Al-Kitaab.com. All rights reserved."
  },

  de: {
    SurahAlKahf: "Surah Al Kahf",
    Pause: "Pause",
    SurahInfo: "Über die Sure",
    Reciters: "Rezitator",
    Copied: "Kopiert",
    Settings: "Einstellungen",
    Reading: "Lesen",
    Nightmode: "Nachtmodus",
    Daymode: "Tagmodus",
    Translations: "Übersetzungen",
    Tooltip: "Knopinfo",
    FontSize: "Schriftgröße",
    Arabic: "Arabisch",
    Translation: "Übersetzung",
    Verses: "Verse",
    Surahs: "Suren",
    Play: "Abspielen",
    Copy: "Kopieren",
    NextSurah: "Nächste Sure",
    PreviousSurah: "Vorherige Sure",
    BeginningofSurah: "Beginn der Sure",
    Home: "Start",
    Islam: "Islam",
    Help: "Helpen",
    Feed: "Terugkoppeling",
    Contri: "Bijdragen",
    Mobile: "Mobiel",
    Dev: "Developers",
    Langs: "Sprachen",
    placeholder: "Suchen...",
    Quick: "Schnellzugang",
    All: "Alle",
    Makki: "Mekkanische Koransuren",
    Madni: "Medinensische Koransuren",
    Manzil: "Manzil",
    SurahYasin: "Surah Yasin (Yaseen)",
    SurahArRahman: "Surah Ar-Rahman",
    SurahAlMulk: "Surah Al Mulk",
    AyatulKursi: "Ayatul Kursi",
    Site: "Plaats",
    Prayer: "Gebedstijden",
    About: "Over Ons",
    Contact: "Contact Ons",
    Footertext:
      "Al-kitaab.com (ook bekend als de nobele koran, al koran, heilige koran, koran) is een pro bono-project.",
    FootCopy: "2019 Al-Kitaab.com. Alle rechten voorbehouden."
  },

  id: {
    SurahAlKahf: "Surah Al Kahf",
    Pause: "Jeda",
    SurahInfo: "Tentang Surah",
    Reciters: "Qari",
    Copied: "Disalin",
    Settings: "Pengaturan",
    Reading: "Mengaji Sendiri",
    Nightmode: "Mode Malam Hari",
    Daymode: "Mode Siang Hari",
    Translations: "Terjemahan",
    Tooltip: "Tip alat",
    FontSize: "Ukuran Font",
    Arabic: "Arab",
    Translation: "Terjemahan",
    Verses: "Ayat",
    Surahs: "Surah",
    Play: "Perdengarkan",
    Copy: "Salin",
    NextSurah: "Surah Berikutnya",
    PreviousSurah: "Surah Sebelumnya",
    BeginningofSurah: "Awal Surah",
    Home: "Beranda",
    Islam: "Islam",
    Help: "Membantu",
    Feed: "Umpan balik",
    Contri: "Menyumbang",
    Mobile: "Mobile",
    Dev: "Pengembang",
    Langs: "Bahasa",
    placeholder: "Cari Sesuatu...",
    Quick: "Tautan langsung",
    All: "Semua",
    Makki: "Surah Makkiyah",
    Madni: "Surah Madaniyah",
    Manzil: "Manzil",
    SurahYasin: "Surah Yasin (Yaseen)",
    SurahArRahman: "Surah Ar-Rahman",
    SurahAlMulk: "Surah Al Mulk",
    AyatulKursi: "Ayatul Kursi",
    Site: "Tempat terletak",
    Prayer: "Waktu sholat",
    About: "Tentang kami",
    Contact: "Hubungi kami",
    Footertext:
      "Al-kitaab.com (juga dikenal sebagai quran mulia, al quran, quran suci, koran) adalah proyek pro bono.",
    FootCopy: "2019 Al-Kitaab.com. Seluruh hak cipta."
  },

  ar: {
    SurahAlKahf: "Surah Al Kahf",
    Pause: "وقف",
    SurahInfo: "معلومات عن السورة",
    Reciters: "القراء",
    Copied: "نسخ",
    Settings: "الإعدادات",
    Reading: "قراءة",
    Nightmode: "الوضع الليلي",
    Daymode: "الوضع النهاري",
    Translations: "ترجمة",
    Tooltip: "تلميح",
    FontSize: "حجم الخط",
    Arabic: "عربى",
    Translation: "ترجمة",
    Verses: "الآيات",
    Surahs: "السور",
    Play: "تشغيل",
    Copy: "نسخ",
    NextSurah: "السورة التالية",
    PreviousSurah: "السورة السابقة",
    BeginningofSurah: "بداية السورة",
    Home: "الصفحة الرئيسية",
    Islam: "الاسلام",
    Help: "مساعدة",
    Feed: "ردود الفعل",
    Contri: "تساهم",
    Mobile: "التليفون المحمول",
    Dev: "المطورون",
    Langs: "اللغات",
    placeholder: "البحث ...",
    Quick: "روابط سريعة",
    All: "جميع السور",
    Makki: "السور المكية",
    Madni: "السور المدنية",
    Manzil: "Manzil",
    SurahYasin: "Surah Yasin (Yaseen)",
    SurahArRahman: "Surah Ar-Rahman",
    SurahAlMulk: "Surah Al Mulk",
    AyatulKursi: "آية الكرسي",
    Site: "موقع",
    Prayer: "أوقات الصلاة",
    About: "معلومات عنا",
    Contact: "اتصل بنا",
    Footertext:
      ".(المعروف أيضًا باسم القرآن الكريم ، القرآن ، القرآن الكريم ، القرآن) هو مشروع مجاني Al- Kitaab.com",
    FootCopy: "2019 كتاب. كل الحقوق محفوظة."
  },

  nl: {
    SurahAlKahf: "Surah Al Kahf",
    Pause: "Pauze",
    SurahInfo: "Over de Soera",
    Reciters: "Vertellers",
    Copied: "Gekopieerde",
    Settings: "Instellingen",
    Reading: "Lezen",
    Nightmode: "Nachtmodus",
    Daymode: "Dagstand",
    Translations: "Vertalingen",
    Tooltip: "Knopinfo",
    FontSize: "Lettergrootte",
    Arabic: "Arabisch",
    Translation: "Vertaling",
    Verses: "Verzen",
    Surahs: "Soera's",
    Play: "Afspelen",
    Copy: "Kopiëren",
    NextSurah: "Volgende Soera",
    PreviousSurah: "Vorige Soera",
    BeginningofSurah: "Begin van de Soera",
    Home: "Startpagina",
    Islam: "Islam",
    Help: "Helpen",
    Feed: "Geri bildirim",
    Contri: "Katkıda bulunmak",
    Mobile: "Seyyar",
    Dev: "Geliştiriciler",
    Langs: "Talen",
    placeholder: "Doorzoek alles...",
    Quick: "Directe link",
    All: "Allemaal",
    Makki: "Makki Soera's van de Koran",
    Madni: "Madini Soera's van de Koran",
    Manzil: "Manzil",
    SurahYasin: "Surah Yasin (Yaseen)",
    SurahArRahman: "Surah Ar-Rahman",
    SurahAlMulk: "Surah Al Mulk",
    AyatulKursi: "Ayatul Kursi",
    Site: "Yer",
    Prayer: "Ibadet zamanları",
    About: "Hakkımızda",
    Contact: "Bizimle iletişime geçin",
    Footertext:
      "Alkitaab.com (asil Kur'an, Al Kur'an, Kur'an-ı Kerim olarak da bilinir) yanlısı bir bono projesidir.",
    FootCopy: "2019 Al-Kitaab.com. Tüm hakları Saklıdır."
  },

  fr: {
    SurahAlKahf: "Surah Al Kahf",
    Pause: "Pause",
    SurahInfo: "À propos de la sourate",
    Reciters: "Récitateurs",
    Copied: "Copié",
    Settings: "Paramètres",
    Reading: "lire",
    Nightmode: "Mode nuit",
    Daymode: "Mode jour",
    Translations: "Traductions",
    Tooltip: "Info-bulle",
    FontSize: "Taille de police",
    Arabic: "Arabe",
    Translation: "Traduction",
    Verses: "Versets",
    Surahs: "Sourates",
    Play: "Lecture",
    Copy: "Copier",
    NextSurah: "La sourate suivante",
    PreviousSurah: "La sourate précédente",
    BeginningofSurah: "Le début de la sourate",
    Home: "Accueil",
    Islam: "Islame",
    Help: "Aidez-moi",
    Feed: "Retour d'information",
    Contri: "Contribuer",
    Mobile: "Mobile",
    Dev: "Développeurs",
    Langs: "Langues",
    placeholder: "Rechercher...",
    Quick: "Lien directe",
    All: "Tout",
    Makki: "Les sourates Makki du Coran",
    Madni: "Les sourates Madini du Coran",
    Manzil: "Manzil",
    SurahYasin: "Surah Yasin (Yaseen)",
    SurahArRahman: "Surah Ar-Rahman",
    SurahAlMulk: "Surah Al Mulk",
    AyatulKursi: "Ayatul Kursi",
    Site: "Site",
    Prayer: "Temps de prière",
    About: "À propos de nous",
    Contact: "Contactez nous",
    Footertext:
      "Al-kitaab.com (également connu sous le nom de noble coran, al coran, saint coran, coran) est un projet bénévole.",
    FootCopy: "2019 Al-Kitaab.com. Tous les droits sont réservés."
  },

  ur: {
    SurahAlKahf: "Surah Al Kahf",
    Pause: "توقف",
    SurahInfo: "سورۃ کے متعلق",
    Reciters: "قراء",
    Copied: "نقل شدہ",
    Settings: "ترتیبات",
    Reading: "تلاوت",
    Nightmode: "نائٹ موڈ",
    Daymode: "ڈے موڈ",
    Translations: "تراجم",
    Tooltip: "ٹول ٹپ",
    FontSize: "فونٹ سائز",
    Arabic: "عربی",
    Translation: "ترجمہ",
    Verses: "آیات",
    Surahs: "سورتیں",
    Play: "چلائیں",
    Copy: "نقل کریں",
    NextSurah: "اگلی سورہ",
    PreviousSurah: "پچھلی سورہ",
    BeginningofSurah: "آغاز سورۃ",
    Home: "ہوم",
    Islam: "اسلام",
    Help: "مدد",
    Feed: "آراء",
    Contri: "تعاون کریں",
    Mobile: "موبائل",
    Dev: "ڈویلپرز",
    Langs: "زبانیں",
    placeholder: "…کچھ بھی تلاش کریں",
    Quick: "فوری روابط",
    All: "سب",
    Makki: "قرآن کی مکی سورتیں",
    Madni: "قرآن کی مدنی سورتیں",
    Manzil: "Manzil",
    SurahYasin: "Surah Yasin (Yaseen)",
    SurahArRahman: "Surah Ar-Rahman",
    SurahAlMulk: "Surah Al Mulk",
    AyatulKursi: "آية الكرسي",
    Site: "سائٹ",
    Prayer: "نماز کے اوقات",
    About: "ہمارے بارے میں",
    Contact: "ہم سے رابطہ کریں",
    Footertext:
      "Al-kitaab.com(بطور نوبل قرآن ، القرآن ، قرآن پاک ، کوران بھی کہا جاتا ہے) ایک بنو پروجیکٹ ہے۔",
    FootCopy: "2019 Al-Kitaab.com. جملہ حقوق محفوظ ہیں."
  },

  tr: {
    SurahAlKahf: "Surah Al Kahf",
    Pause: "Duraklat",
    SurahInfo: "Sure Hakkında",
    Reciters: "Kariler",
    Copied: "Kopyalandı",
    Settings: "Ayarlar",
    Reading: "Okuma",
    Nightmode: "Gece modu",
    Daymode: "Gündüz Modu",
    Translations: "Mealler",
    Tooltip: "Ipucu",
    FontSize: "Yazı Boyutu",
    Arabic: "Arapça",
    Translation: "Meal",
    Verses: "Ayetler",
    Surahs: "Sureler",
    Play: "Başlat",
    Copy: "Kopyala",
    NextSurah: "Sonraki Sure",
    PreviousSurah: "Önceki Sure",
    BeginningofSurah: "Surenin Başı",
    Home: "Ana Sayfa",
    Islam: "İslam",
    Help: "Help",
    Feed: "Feedback",
    Contri: "Contribute",
    Mobile: "Mobile",
    Dev: "Developers",
    Langs: "Diller",
    placeholder: "Arama Yap...",
    Quick: "Doğrudan bağlantı",
    All: "Tüm Sureler",
    Makki: "Mekki Sureler",
    Madni: "Medeni Sureler",
    Manzil: "Manzil",
    SurahYasin: "Surah Yasin (Yaseen)",
    SurahArRahman: "Surah Ar-Rahman",
    SurahAlMulk: "Surah Al Mulk",
    AyatulKursi: "Ayatul Kursi",
    Site: "Site",
    Prayer: "Prayer times",
    About: "About Us",
    Contact: "Contact Us",
    Footertext:
      "Al-kitaab.com (also known as the noble quran, al quran, holy quran, koran) is a pro bono project.",
    FootCopy: "2019 Al-Kitaab.com. All rights reserved."
  },

  bg: {
    SurahAlKahf: "Surah Al Kahf",
    Pause: "Пауза",
    SurahInfo: "Относно Сура",
    Reciters: "Рецитатори",
    Copied: "Копиран",
    Settings: "Настройки",
    Reading: "Прочитане",
    Nightmode: "Нощен режим",
    Daymode: "Дневен режим",
    Translations: "Преводи",
    Tooltip: "Knopinfo",
    FontSize: "Размер на шрифта",
    Arabic: "Арабски",
    Translation: "Превод",
    Verses: "Стихове",
    Surahs: "Сури",
    Play: "Изпълни",
    Copy: "Копирай",
    NextSurah: "Следваща Сура",
    PreviousSurah: "Предишна Сура",
    BeginningofSurah: "Начало на Сура",
    Home: "Начало",
    Islam: "Ислям",
    Help: "Helpen",
    Feed: "Geri bildirim",
    Contri: "Katkıda bulunmak",
    Mobile: "Seyyar",
    Dev: "Geliştiriciler",
    Langs: "Езици",
    placeholder: "Потърси навсякъде...",
    Quick: "Директен линк",
    All: "Всичкo",
    Makki: "Мекански Сури от Корана",
    Madni: "Медински Сури от Корана",
    Manzil: "Manzil",
    SurahYasin: "Surah Yasin (Yaseen)",
    SurahArRahman: "Surah Ar-Rahman",
    SurahAlMulk: "Surah Al Mulk",
    AyatulKursi: "Ayatul Kursi",
    Site: "Yer",
    Prayer: "Ibadet zamanları",
    About: "Hakkımızda",
    Contact: "Bizimle iletişime geçin",
    Footertext:
      "Alkitaab.com (asil Kur'an, Al Kur'an, Kur'an-ı Kerim olarak da bilinir) yanlısı bir bono projesidir.",
    FootCopy: "2019 Al-Kitaab.com. Tüm hakları Saklıdır."
  },

  no: {
    SurahAlKahf: "Surah Al Kahf",
    Pause: "Om Surahen",
    SurahInfo: "Surah Info",
    Reciters: "Reciters",
    Copied: "Kopiert",
    Settings: "Innstillinger",
    Reading: "Lesning",
    Nightmode: "Nattmodus",
    Daymode: "Dagmodus",
    Translations: "Oversettelser",
    Tooltip: "Tooltip",
    FontSize: "Skriftstørrelse",
    Arabic: "Arabisk",
    Translation: "Oversettelse",
    Verses: "Versene",
    Surahs: "Surahene",
    Play: "Spille",
    Copy: "Kopiere",
    NextSurah: "Neste Surah",
    PreviousSurah: "Forrige Surah",
    BeginningofSurah: "Begynnelsen av Surah",
    Home: "Hjem",
    Islam: "Islam",
    Help: "Help",
    Feed: "Feedback",
    Contri: "Contribute",
    Mobile: "Mobile",
    Dev: "Developers",
    Langs: "Språk",
    placeholder: "Søk på hva som helst...",
    Quick: "Direkte kobling",
    All: "Alle",
    Makki: "Makki Surahene av Koranen",
    Madni: "Madini Surahene av Koranen",
    Manzil: "Manzil",
    SurahYasin: "Surah Yasin (Yaseen)",
    SurahArRahman: "Surah Ar-Rahman",
    SurahAlMulk: "Surah Al Mulk",
    AyatulKursi: "Ayatul Kursi",
    Site: "Site",
    Prayer: "Prayer times",
    About: "About Us",
    Contact: "Contact Us",
    Footertext:
      "Al-kitaab.com (also known as the noble quran, al quran, holy quran, koran) is a pro bono project.",
    FootCopy: "2019 Al-Kitaab.com. All rights reserved."
  },

  sv: {
    SurahAlKahf: "Surah Al Kahf",
    Pause: "Pausa",
    SurahInfo: "Om Surat",
    Reciters: "Uppläsare",
    Copied: "Kopierat",
    Settings: "Inställningar",
    Reading: "Läsning",
    Nightmode: "Nattläge",
    Daymode: "Dagläge",
    Translations: "Översättningar",
    Tooltip: "Tooltip",
    FontSize: "Textstorlek",
    Arabic: "Arabiska",
    Translation: "Översättning",
    Verses: "Verser",
    Surahs: "Suror",
    Play: "Spela upp",
    Copy: "Kopiera",
    NextSurah: "Nästa Surat",
    PreviousSurah: "Föregående Surat",
    BeginningofSurah: "Början av Surat",
    Home: "Hem",
    Islam: "Islam",
    Help: "Help",
    Feed: "Feedback",
    Contri: "Contribute",
    Mobile: "Mobile",
    Dev: "Developers",
    Langs: "Språk",
    placeholder: "Sök...",
    Quick: "Direktlänk",
    All: "Allt",
    Makki: "Mekka-suror från Koranen",
    Madni: "Medina-suror från Koranen",
    Manzil: "Manzil",
    SurahYasin: "Surah Yasin (Yaseen)",
    SurahArRahman: "Surah Ar-Rahman",
    SurahAlMulk: "Surah Al Mulk",
    AyatulKursi: "Ayatul Kursi",
    Site: "Site",
    Prayer: "Prayer times",
    About: "About Us",
    Contact: "Contact Us",
    Footertext:
      "Al-kitaab.com (also known as the noble quran, al quran, holy quran, koran) is a pro bono project.",
    FootCopy: "2019 Al-Kitaab.com. All rights reserved."
  },

  ru: {
    SurahAlKahf: "Surah Al Kahf",
    Pause: "Пауза",
    SurahInfo: "О суре",
    Reciters: "Чтецы",
    Copied: "Скопировано",
    Settings: "Настройки",
    Reading: "Чтение",
    Nightmode: "Ночной режим",
    Daymode: "Дневной режим",
    Translations: "Перевод",
    Tooltip: "Tooltip",
    FontSize: "Размер шрифта",
    Arabic: "Арабский",
    Translation: "Перевод",
    Verses: "Стихи",
    Surahs: "Суры",
    Play: "Воспроизвести",
    Copy: "Скопировать",
    NextSurah: "Следующая сура",
    PreviousSurah: "Предыдущая сура",
    BeginningofSurah: "В начало",
    Home: "Главная",
    Islam: "Ислам",
    Help: "Help",
    Feed: "Feedback",
    Contri: "Contribute",
    Mobile: "Mobile",
    Dev: "Developers",
    Langs: "Языки",
    placeholder: "Поиск...",
    Quick: "Прямая ссылка",
    All: "Все",
    Makki: "Мекканские суры",
    Madni: "Мединские суры",
    Manzil: "Manzil",
    SurahYasin: "Surah Yasin (Yaseen)",
    SurahArRahman: "Surah Ar-Rahman",
    SurahAlMulk: "Surah Al Mulk",
    AyatulKursi: "Ayatul Kursi",
    Site: "Site",
    Prayer: "Prayer times",
    About: "About Us",
    Contact: "Contact Us",
    Footertext:
      "Al-kitaab.com (also known as the noble quran, al quran, holy quran, koran) is a pro bono project.",
    FootCopy: "2019 Al-Kitaab.com. All rights reserved."
  },
  it: {
    SurahAlKahf: "Surah Al Kahf",
    Pause: "Pausa",
    SurahInfo: "Sulla sura",
    Reciters: "Recitatori",
    Copied: "Copiato",
    Settings: "Impostazioni",
    Reading: "Lettura",
    Nightmode: "Modalità ‘’scuro’’",
    Daymode: "Modalità ‘’chiaro''",
    Translations: "Traduzioni",
    Tooltip: "Tooltip",
    FontSize: "Dimensione dei caratteri",
    Arabic: "In arabo",
    Translation: "Traduzione",
    Verses: "Versetti",
    Surahs: "Sure",
    Play: "Avviare la registrazione",
    Copy: "Copiare ",
    NextSurah: "La prossima sura",
    PreviousSurah: "La sura precedente",
    BeginningofSurah: "L’inizio della sura",
    Home: "Home",
    Islam: "Islam",
    Help: "Help",
    Feed: "Feedback",
    Contri: "Contribute",
    Mobile: "Mobile",
    Dev: "Developers",
    Langs: "Lingua",
    placeholder: "Cerca...",
    Quick: "Link diretto",
    All: "Tutte",
    Makki: "Sure del periodo meccano",
    Madni: "Sure del periodo medinese",
    Manzil: "Manzil",
    SurahYasin: "Surah Yasin (Yaseen)",
    SurahArRahman: "Surah Ar-Rahman",
    SurahAlMulk: "Surah Al Mulk",
    AyatulKursi: "Ayatul Kursi",
    Site: "Site",
    Prayer: "Prayer times",
    About: "About Us",
    Contact: "Contact Us",
    Footertext:
      "Al-kitaab.com (also known as the noble quran, al quran, holy quran, koran) is a pro bono project.",
    FootCopy: "2019 Al-Kitaab.com. All rights reserved."
  },
  bs: {
    SurahAlKahf: "Surah Al Kahf",
    Pause: "Pauza",
    SurahInfo: "O suri",
    Reciters: "Učači",
    Copied: "Kopirano",
    Settings: "Podešavanja",
    Reading: "Čitanje",
    Nightmode: "Noćni način rada",
    Daymode: "Dnevni način rada",
    Translations: "Prijevodi",
    Tooltip: "Tooltip",
    FontSize: "Veličina slova",
    Arabic: "Arapski - veličina slova",
    Translation: "Prijevod - veličina slova",
    Verses: "Ajeti",
    Surahs: "Sureta",
    Play: "Slušaj",
    Copy: "Kopiraj",
    NextSurah: "Sljedeća sura",
    PreviousSurah: "Prethodna sura",
    BeginningofSurah: "Početak sure",
    Home: "Početna stranica",
    Islam: "Islam",
    Help: "Help",
    Feed: "Feedback",
    Contri: "Contribute",
    Mobile: "Mobile",
    Dev: "Developers",
    Langs: "Jezici",
    placeholder: "Potražite...",
    Quick: "Direktna poveznica",
    All: "Sve sure",
    Makki: "Kur'anske sure objavljene u Mekki",
    Madni: "Kur'anske sure objavljene u Medini",
    Manzil: "Manzil",
    SurahYasin: "Surah Yasin (Yaseen)",
    SurahArRahman: "Surah Ar-Rahman",
    SurahAlMulk: "Surah Al Mulk",
    AyatulKursi: "Ayatul Kursi",
    Site: "Site",
    Prayer: "Prayer times",
    About: "About Us",
    Contact: "Contact Us",
    Footertext:
      "Al-kitaab.com (also known as the noble quran, al quran, holy quran, koran) is a pro bono project.",
    FootCopy: "2019 Al-Kitaab.com. All rights reserved."
  },
  es: {
    SurahAlKahf: "Surah Al Kahf",
    Pause: "Pausa",
    SurahInfo: "Sobre el Sura",
    Reciters: "Recitadores",
    Copied: "Copiado",
    Settings: "Ajustes",
    Reading: "Lectura",
    Nightmode: "Modo noche",
    Daymode: "Modo día",
    Translations: "Traducciones",
    Tooltip: "Tooltip",
    FontSize: "Tamaño de fuente",
    Arabic: "Tamaño de fuente árabe",
    Translation: "Traducción",
    Verses: "Versos",
    Surahs: "Suras",
    Play: "Reproducir",
    Copy: "Copiar",
    NextSurah: "Sura siguiente",
    PreviousSurah: "Sura Anterior",
    BeginningofSurah: "Inicio del Sura",
    Home: "Inicio",
    Islam: "Islam",
    Help: "Help",
    Feed: "Feedback",
    Contri: "Contribute",
    Mobile: "Mobile",
    Dev: "Developers",
    Langs: "Idiomas",
    placeholder: "Búsqueda en el sitio...",
    Quick: "Vínculo directo",
    All: "Ver completo",
    Makki: "Suras Makki del Corán",
    Madni: "Suras Madaní del Corán",
    Manzil: "Manzil",
    SurahYasin: "Surah Yasin (Yaseen)",
    SurahArRahman: "Surah Ar-Rahman",
    SurahAlMulk: "Surah Al Mulk",
    AyatulKursi: "Ayatul Kursi",
    Site: "Site",
    Prayer: "Prayer times",
    About: "About Us",
    Contact: "Contact Us",
    Footertext:
      "Al-kitaab.com (also known as the noble quran, al quran, holy quran, koran) is a pro bono project.",
    FootCopy: "2019 Al-Kitaab.com. All rights reserved."
  },
  pt: {
    SurahAlKahf: "Surah Al Kahf",
    Pause: "Pausa",
    SurahInfo: "Sobre a Sura",
    Reciters: "Declamadores",
    Copied: "Copiado",
    Settings: "Configurações",
    Reading: "Lendo",
    Nightmode: "Modo noturno",
    Daymode: "Modo diurno",
    Translations: "Traduções",
    Tooltip: "Tooltip",
    FontSize: "Tamanho da fonte",
    Arabic: "Árabe",
    Translation: "Tradução",
    Verses: "Versos",
    Surahs: "Capitulos",
    Play: "Tocar",
    Copy: "Copiar",
    NextSurah: "Próximo Surah (capítulo)",
    PreviousSurah: "Surah (capítulo) anterior",
    BeginningofSurah: "Começar o Surah (capítulo)",
    Home: "Início",
    Islam: "Islã",
    Help: "Help",
    Feed: "Feedback",
    Contri: "Contribute",
    Mobile: "Mobile",
    Dev: "Developers",
    Langs: "Línguas",
    placeholder: "Procurar...",
    Quick: "Link direto",
    All: "Tudo",
    Makki: "Makki Surahs do Alcorão",
    Madni: "Madini Surahs do Alcorão",
    Manzil: "Manzil",
    SurahYasin: "Surah Yasin (Yaseen)",
    SurahArRahman: "Surah Ar-Rahman",
    SurahAlMulk: "Surah Al Mulk",
    AyatulKursi: "Ayatul Kursi",
    Site: "Site",
    Prayer: "Prayer times",
    About: "About Us",
    Contact: "Contact Us",
    Footertext:
      "Al-kitaab.com (also known as the noble quran, al quran, holy quran, koran) is a pro bono project.",
    FootCopy: "2019 Al-Kitaab.com. All rights reserved."
  },
  fa: {
    SurahAlKahf: "Surah Al Kahf",
    Pause: "وقفه در پخش",
    SurahInfo: "درباره سوره",
    Reciters: "تلاوت کننده",
    Copied: "ضبط شده",
    Settings: "تنظیمات",
    Reading: "خوانش",
    Nightmode: "حالت شب",
    Daymode: "حالت روز",
    Translations: "ترجمه ها",
    Tooltip: "Tooltip",
    FontSize: "سایز قلم",
    Arabic: "عربی",
    Translation: "ترجمه",
    Verses: "آیات",
    Surahs: "سوره ها",
    Play: "پخش",
    Copy: "کپی",
    NextSurah: "سوره بعدی",
    PreviousSurah: "سوره قبلی",
    BeginningofSurah: "شروع سوره",
    Home: "خانه",
    Islam: "اسلام",
    Help: "Help",
    Feed: "Feedback",
    Contri: "Contribute",
    Mobile: "Mobile",
    Dev: "Developers",
    Langs: "زبان ها",
    placeholder: "...جستجو",
    Quick: "لینک مستقیم",
    All: "همه",
    Makki: "سوره های مکی قرآن",
    Madni: "سوره های مدنی قرآن",
    Manzil: "Manzil",
    SurahYasin: "Surah Yasin (Yaseen)",
    SurahArRahman: "Surah Ar-Rahman",
    SurahAlMulk: "Surah Al Mulk",
    AyatulKursi: "Ayatul Kursi",
    Site: "Site",
    Prayer: "Prayer times",
    About: "About Us",
    Contact: "Contact Us",
    Footertext:
      "Al-kitaab.com (also known as the noble quran, al quran, holy quran, koran) is a pro bono project.",
    FootCopy: "2019 Al-Kitaab.com. All rights reserved."
  },
  sq: {
    SurahAlKahf: "Surah Al Kahf",
    Pause: "Pushim",
    SurahInfo: "Rreth Sures",
    Reciters: "Recituesit",
    Copied: "Kopjuar",
    Settings: "Cilësimet",
    Reading: "Lexim",
    Nightmode: "Metoda e natës",
    Daymode: "Metoda e ditës",
    Translations: "Përkthimet",
    Tooltip: "Tooltip",
    FontSize: "Përmasa e Shkronjave",
    Arabic: "Arabisht",
    Translation: "Përkthim",
    Verses: "Vargjet",
    Surahs: "Suret",
    Play: "Luaj",
    Copy: "Kopje",
    NextSurah: "Sureja tjetër",
    PreviousSurah: "Sureja paraprake",
    BeginningofSurah: "Sureja fillestare",
    Home: "Ballina",
    Islam: "Islami",
    Help: "Help",
    Feed: "Feedback",
    Contri: "Contribute",
    Mobile: "Mobile",
    Dev: "Developers",
    Langs: "Gjuhët",
    placeholder: "Kërkoni ndonjë gjë...",
    Quick: "Lidhje direkte",
    All: "Të gjitha",
    Makki: "Suret e Kuranit për Mekën",
    Madni: "Suret e Kuranit për Medinën",
    Manzil: "Manzil",
    SurahYasin: "Surah Yasin (Yaseen)",
    SurahArRahman: "Surah Ar-Rahman",
    SurahAlMulk: "Surah Al Mulk",
    AyatulKursi: "Ayatul Kursi",
    Site: "Site",
    Prayer: "Prayer times",
    About: "About Us",
    Contact: "Contact Us",
    Footertext:
      "Al-kitaab.com (also known as the noble quran, al quran, holy quran, koran) is a pro bono project.",
    FootCopy: "2019 Al-Kitaab.com. All rights reserved."
  },
  da: {
    SurahAlKahf: "Surah Al Kahf",
    Pause: "Pause",
    SurahInfo: "Om Suraen",
    Reciters: "Fortællere",
    Copied: "Kopieret",
    Settings: "Indstillinger",
    Reading: "Læser",
    Nightmode: "Nattetilstand",
    Daymode: "Dag-tilstand",
    Translations: "Oversættelser",
    Tooltip: "Tooltip",
    FontSize: "Skriftsstørrelse",
    Arabic: "Arabisk",
    Translation: "Oversættelse",
    Verses: "Vers",
    Surahs: "Suraer",
    Play: "Afspil",
    Copy: "Kopier",
    NextSurah: "Næste Sura",
    PreviousSurah: "Forrige Sura",
    BeginningofSurah: "Begyndelsen af Sura",
    Home: "Hjem ",
    Islam: "Islam",
    Help: "Help",
    Feed: "Feedback",
    Contri: "Contribute",
    Mobile: "Mobile",
    Dev: "Developers",
    Langs: "Sprog",
    placeholder: "Søg hvad som helst...",
    Quick: "Direkte link",
    All: "Alle",
    Makki: "Makki Suraer i Koranen",
    Madni: "Madinier Suraer i Koranen",
    Manzil: "Manzil",
    SurahYasin: "Surah Yasin (Yaseen)",
    SurahArRahman: "Surah Ar-Rahman",
    SurahAlMulk: "Surah Al Mulk",
    AyatulKursi: "Ayatul Kursi",
    Site: "Site",
    Prayer: "Prayer times",
    About: "About Us",
    Contact: "Contact Us",
    Footertext:
      "Al-kitaab.com (also known as the noble quran, al quran, holy quran, koran) is a pro bono project.",
    FootCopy: "2019 Al-Kitaab.com. All rights reserved."
  },
fi: {
    SurahAlKahf: "Surah Al Kahf",
    Pause: "Tauko",
    SurahInfo: "Tietoa suurasta",
    Reciters: "Lausuja",
    Copied: "Kopioitu",
    Settings: "Asetukset",
    Reading: "Lukutila",
    Nightmode: "Yötila",
    Daymode: "Päivätila",
    Translations: "Käännökset",
    Tooltip: "Tooltip",
    FontSize: "Fontin koko",
    Arabic: "Arabia",
    Translation: "Käännös",
    Verses: "Jakeet",
    Surahs: "Suurat",
    Play: "Toista",
    Copy: "Kopioi",
    NextSurah: "Seuraava suura",
    PreviousSurah: "Edellinen suura",
    BeginningofSurah: "Suuran alku",
    Home: "Aloitussivu",
    Islam: "Islam",
    Help: "Help",
    Feed: "Feedback",
    Contri: "Contribute",
    Mobile: "Mobile",
    Dev: "Developers",
    Langs: "Kielet",
    placeholder: "Etsi...",
    Quick: "Suora linkki",
    All: "Kaikki suurat",
    Makki: "Mekan suurat",
    Madni: "Medinan suurat",
    Manzil: "Manzil",
    SurahYasin: "Surah Yasin (Yaseen)",
    SurahArRahman: "Surah Ar-Rahman",
    SurahAlMulk: "Surah Al Mulk",
    AyatulKursi: "Ayatul Kursi",
    Site: "Site",
    Prayer: "Prayer times",
    About: "About Us",
    Contact: "Contact Us",
    Footertext:
      "Al-kitaab.com (also known as the noble quran, al quran, holy quran, koran) is a pro bono project.",
    FootCopy: "2019 Al-Kitaab.com. All rights reserved."
  },

 


};
